Add DeploymentGeneratorService parsed flows test
KaotoIO/kaoto-backend pull request #647
Opened 2023-05-10 11:22 UTC by tplevko

Found the flow parsing was adding the '---' at the end of parsed yaml I think it might be cut off.

@Delawen please have a look.

2023-05-10 11:29 UTC, Delawen approved these changes

2023-05-10 11:30 UTC, Delawen commented
Good catch!

2023-05-11 08:07 UTC, Delawen commented
Could be some issue with new lines in windows? Tests fail too much.

2023-05-11 08:08 UTC, Delawen requested changes

2023-05-11 08:08 UTC, Delawen commented on camel-route-support/src/test/java/io/kaoto/backend/api/service/deployment/generator/camelroute/DeploymentGeneratorServiceTest.java
> +        assertEquals(yaml, yaml2);
Can you use `assertThat(yaml).isEqualToNormalizingNewlines(yaml2)` instead?

2023-05-15 10:25 UTC, tplevko commented
@Delawen I updated also the KameletBinding and Kamelets DeploymentGeneratorServices.

I'm still trying to bypass the windows issues, the `isEqualToNormalizingNewlines` doesn't seem to have helped, so trying other things too

2023-05-15 12:03 UTC, tplevko commented
This should be ready for review - the `native tests for windows-latest` failure seems to be unrelated to this PR

2023-05-16 07:31 UTC, Delawen approved these changes

2023-05-16 09:48 UTC, merged